// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChoosePreviousQuestionsController from "./choose_previous_questions_controller"
application.register("choose-previous-questions", ChoosePreviousQuestionsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import { Application } from "@hotwired/stimulus"
import { definitionsFromContext } from "@hotwired/stimulus-webpack-helpers"

window.Stimulus = Application.start()
const context = require.context("./controllers", true, /\.js$/)
Stimulus.load(definitionsFromContext(context))
import PopupController from "./popup_controller"
application.register("popup", PopupController)

import SearchCampaignsController from "./search_campaigns_controller"
application.register("search-campaigns", SearchCampaignsController)
