// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddQuestionOptionController from "./add_question_option_controller"
application.register("add-question-option", AddQuestionOptionController)

import CampaignCardController from "./campaign_card_controller"
application.register("campaign-card", CampaignCardController)

import CheckedController from "./checked_controller"
application.register("checked", CheckedController)

import ChoosePreviousQuestionsController from "./choose_previous_questions_controller"
application.register("choose-previous-questions", ChoosePreviousQuestionsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PopupController from "./popup_controller"
application.register("popup", PopupController)

import QuestionFormController from "./question_form_controller"
application.register("question-form", QuestionFormController)

import SearchCampaignsController from "./search_campaigns_controller"
application.register("search-campaigns", SearchCampaignsController)
